// Portfolio / case studies. Every page that shows work reads from here.
//
// Rules (from the blueprint):
//  - Real projects only. No invented clients, testimonials, or numbers.
//  - "result" describes what became easier, never an unmeasured outcome.
//  - Set `published: false` to keep a project off the site until it's ready.
//
// Screenshots live in public/work (generated by scripts/optimize-shots.mjs).
// TODO(owner): review each project's wording and confirm each client is OK being listed.

export type ProjectType =
  | 'Website'
  | 'Website + forms'
  | 'CRM / system'
  | 'Payments / POS'
  | 'Internal workflow'
  | 'Website + business system';

export interface Project {
  id: string;
  published: boolean;
  featured: boolean;
  business: string;
  location: string;
  industry: string;
  types: ProjectType[];
  problem: string;
  built: string;
  result: string;
  builtList?: string[];
  url?: string;
  urlLabel?: string;
  image?: { desktop: string; desktopSmall: string; mobile?: string; alt: string };
  internal?: boolean;
}

export const projects: Project[] = [
  {
    id: 'bares-taekwondo',
    published: true,
    featured: true,
    internal: true,
    business: 'Bares Taekwondo Fitness',
    location: 'Tyler, TX',
    industry: 'Martial arts school',
    types: ['Website + business system', 'Payments / POS'],
    problem:
      'Off-the-shelf school software cost too much and did not match how the school actually runs.',
    built:
      'A public website with program pages and online checkout, connected to a custom CRM for members, scheduling, payments, and daily operations.',
    result:
      'Members, schedules, agreements, payments, and the website now run on one connected system the school owns.',
    builtList: [
      'Website with program pages and online checkout',
      'Member and household records',
      'Calendar and attendance check-in',
      'Point of sale and recurring billing through Stripe',
      'E-signed membership agreements',
      'Receipts, email, and daily reports',
    ],
    url: 'https://www.barestkd.fit/',
    urlLabel: 'barestkd.fit',
    image: {
      desktop: '/work/barestkd-desktop.webp',
      desktopSmall: '/work/barestkd-desktop-640.webp',
      mobile: '/work/barestkd-mobile.webp',
      alt: 'Bares Taekwondo Fitness website home page',
    },
  },
  {
    id: 'reli-commercial-cleaning',
    published: true,
    featured: true,
    business: 'RELI Commercial Cleaning',
    location: 'Tyler, TX',
    industry: 'Commercial cleaning',
    types: ['Website + business system'],
    problem:
      'The business was on a hosted website builder, and website leads were not connected to how the team ran day-to-day work.',
    built:
      'A rebuilt website with service and service-area pages, plus an operations system for contacts, leads, scheduling, time tracking, and contracts.',
    result:
      'Quote requests from the website land in the same system the team uses to follow up and run jobs.',
    builtList: [
      'Rebuilt website with service and service-area pages',
      'Lead capture wired into their own system',
      'Contacts, lead manager, and scheduling',
      'Staff timesheets and a location-aware time clock',
      'Contract generator and reports',
    ],
    url: 'https://www.relicommercialcleaning.com/',
    urlLabel: 'relicommercialcleaning.com',
    image: {
      desktop: '/work/reli-desktop.webp',
      desktopSmall: '/work/reli-desktop-640.webp',
      mobile: '/work/reli-mobile.webp',
      alt: 'RELI Commercial Cleaning website home page',
    },
  },
  {
    id: '4k-cleaning-solutions',
    published: true,
    featured: true,
    business: '4K Cleaning Solutions',
    location: 'Tyler, TX',
    industry: 'Cleaning services',
    types: ['Website + forms', 'CRM / system'],
    problem:
      'A family-owned cleaning company needed a site that turns visitors into quote requests for several kinds of work.',
    built:
      'A website with pages for each service line, a quote request form, and an operations dashboard for incoming leads.',
    result:
      'Every quote request is sent to the owners right away and tracked in one place.',
    builtList: [
      'Website with pages for office, Airbnb, make-ready, and church cleaning',
      'Quote request form with instant lead notification',
      'Operations dashboard for leads',
      'Contract document',
    ],
    url: 'https://4kcleaningsolutions.com/',
    urlLabel: '4kcleaningsolutions.com',
    image: {
      desktop: '/work/fourk-desktop.webp',
      desktopSmall: '/work/fourk-desktop-640.webp',
      mobile: '/work/fourk-mobile.webp',
      alt: '4K Cleaning Solutions website home page',
    },
  },
  {
    id: 'the-finding-place',
    published: true,
    featured: false,
    business: 'The Finding Place',
    location: 'Tyler, TX',
    industry: 'Micro school',
    types: ['Website + forms', 'CRM / system'],
    problem:
      'A new nature-based school needed to explain its approach clearly and make it easy for families to ask for a tour.',
    built:
      'A website covering programs and philosophy, a tour request form, and a simple admin system for incoming family inquiries.',
    result: 'Tour requests arrive by email and are kept in the school’s own admin view.',
    builtList: [
      'Website with program and philosophy pages',
      'Tour request form with email notification',
      'Admin view for family inquiries',
    ],
    url: 'https://thefinding.place/',
    urlLabel: 'thefinding.place',
    image: {
      desktop: '/work/findingplace-desktop.webp',
      desktopSmall: '/work/findingplace-desktop-640.webp',
      mobile: '/work/findingplace-mobile.webp',
      alt: 'The Finding Place website home page',
    },
  },
  {
    // TODO(owner): publish once the site is live on its domain and the client approves.
    id: 'essential-living-chiropractic',
    published: false,
    featured: false,
    business: 'Essential Living Chiropractic',
    location: 'Tyler, TX',
    industry: 'Chiropractic',
    types: ['Website + forms'],
    problem: 'TODO(owner)',
    built: 'A family chiropractic website with service and local area pages and a lead form.',
    result: 'TODO(owner)',
    url: 'https://essentiallivingchiro.com/',
    urlLabel: 'essentiallivingchiro.com',
  },
];

export const publishedProjects = projects.filter((p) => p.published);
export const featuredProjects = publishedProjects.filter((p) => p.featured);
